sonar.projectKey=TEGRASW_Metropolis-perf_SDG_pseudo-labeling
sonar.projectName=pseudo-labeling
sonar.qualitygate.wait=true
sonar.python.version=3.10

sonar.sources=modules
sonar.tests=tests

sonar.exclusions=\
  **/.venv/**,\
  **/__pycache__/**,\
  **/lightning_logs/**,\
  **/wandb/**,\
  **/*.egg-info/**,\
  **/uv.lock,\
  **/ckpts/**,\
  **/downloads/**,\
  **/output/**,\
  **/input/**,\
  **/persistence/**,\
  **/third_party_licenses/**

sonar.python.coverage.reportPaths=coverage_report.xml
